"""Pydantic request and response schemas for the rewriter inference service."""

from pydantic import BaseModel, Field


class RewriteRequest(BaseModel):
    """Schema for the rewrite prompt request."""

    clinical_note: str = Field(
        ...,
        min_length=1,
        description="Clinical note text to be rewritten.",
    )


class RewriteResponse(BaseModel):
    """Schema for the rewrite prompt response."""

    rewritten_prompt: str = Field(
        ...,
        description="Rewritten prompt generated by phi-3-mini.",
    )
    log_prob_old: float = Field(
        ...,
        description="Log probability of the generated sequence under the current policy.",
    )
    value_estimate: float = Field(
        ...,
        description="Scalar value predicted by the value head.",
    )
